// TN-portfolio/src/components/sections/Header.tsx
import { useState } from "react";
import {
  MdOutlineVisibility,
  MdOutlineVisibilityOff,
  MdOutlineMenu,
} from "react-icons/md";

export default function Header() {
  const [visibility, setVisibility] = useState(false);
  const [showMenu, setShowMenu] = useState(false);
  const buttonSize = 25;
  const buttonPadding = "p-6";
  const headerOpacity = "20";
  const logo = (
    <a
      href="/"
      aria-label="Tam North homepage"
      className={`flex items-center text-2xl whitespace-pre`}
    >
      <span>tam </span>
      <span className="text-4xl">N</span>
      <span>orth</span>
    </a>
  );

  return (
    <header className="group fixed inset-x-0 top-0 flex justify-between items-center bg-transparent text-white transition *:transition font-cinzel">
      <button
        type="button"
        aria-label={`toggle menu visibility ${showMenu ? "off" : "on"}`}
        onClick={() => {
          setShowMenu(!showMenu);
        }}
        className={`hover:scale-110 ${buttonPadding} ${
          visibility || `opacity-${headerOpacity} group-hover:opacity-100`
        }`}
      >
        <MdOutlineMenu size={buttonSize} />
      </button>
      <nav
        aria-label="Main menu"
        className={`absolute left-1/2 -translate-x-1/2 ${
          visibility || `opacity-${headerOpacity} group-hover:opacity-100`
        }`}
      >
        <ul className="grid grid-cols-[1fr_auto_1fr] gap-20 text-center items-center *:hover:scale-110 *:transition">
          <li className="">Options</li>
          <li>{logo}</li>
          <li>Contact</li>
        </ul>
      </nav>
      <button
        type="button"
        aria-label={`toggle header visibility ${visibility ? "off" : "on"}`}
        onClick={() => {
          setVisibility(!visibility);
        }}
        className={`hover:scale-110 ${buttonPadding}`}
      >
        {visibility ? (
          <MdOutlineVisibilityOff size={buttonSize} />
        ) : (
          <MdOutlineVisibility size={buttonSize} />
        )}
      </button>
    </header>
  );
}

// TN-portfolio-sv/src/lib/Header/Header.svelte
<script lang="ts">
	import { resolve } from '$app/paths';
	import { Icon } from 'svelte-icons-pack';
	import { BsEyeFill, BsEyeSlashFill, BsMoonFill, BsSunFill } from 'svelte-icons-pack/bs';

	const homeButtonText = '<span>tam </span><span style="font-size: xx-large">N</span><span>orth</span>';

	// HEADER VISIBILITY FADE
	let visibility = $state(false);
	let headerClass = $derived(visibility ? '' : 'header-hidden');

	// THEME SELECTION
	let isNightMode = $state(true);
	let themeClassNames = ["day-mode", "night-mode"]
	$effect(() => {
		document.body.classList.add(themeClassNames[Number(!isNightMode)]); 
		document.body.classList.remove(themeClassNames[Number(isNightMode)]);
	})
</script>

<!-- <svelte:body class:{themeClassNames[Number(!isNightMode)]}/> -->

<header class="header {headerClass}">
	<nav class="navigation">
		<a href={resolve('/about')} class="header-button">About</a>
		<a href={resolve('/')} aria-label="Tam North homepage" class="header-button home-button">
			{@html homeButtonText}
		</a>
		<a href={resolve('/about')}>About</a>
	</nav>
	<button
		class="header-button"
		onclick={() => (visibility = !visibility)}
		aria-label="toggle header visibility aid {visibility ? 'off' : 'on'}"
	>
		{#if visibility}
			<Icon src={BsEyeFill} />
		{:else}
			<Icon src={BsEyeSlashFill} />
		{/if}
	</button>
	<button
		class="header-button"
		onclick={() => {isNightMode = !isNightMode}}
		aria-label="toggle theme}"
	>
		<Icon src={isNightMode ? BsSunFill : BsMoonFill} />
	</button>
</header>

<style>
	.header {
		font-family: 'Cinzel Decorative';
		position: fixed;
		inset-inline: 0;
		top: 0;
		display: grid;
		grid-template-columns: 1fr 1fr auto 1fr 1fr;
		align-items: center;
		justify-items: center;
		gap: 2rem;
		padding-bottom: 1rem;
		color: var(--text-colour-h1);
	}

	.header-hidden {
		opacity: 20%;
		transition: opacity 0.5s;

		&:hover {
			opacity: 100%;
		}
	}

	.navigation {
		grid-column: 3;
		display: grid;
		grid-template-columns: 1fr auto 1fr;
		align-items: center;
		gap: 2rem;
		text-align: center;
	}

	.header-button {
		transition: scale 0.5s;
		cursor: pointer;

		&:hover {
			scale: 110%;
		}
	}

	.home-button {
		display: flex;
		align-items: center;
		font-size: x-large;
		white-space: pre;
	}
</style>
